"""
Report Generation Agent
Responsible for: formatting financial findings into a clean,
structured markdown executive report — no LLM call needed.
"""

from langchain_core.tools import tool


def make_report_tool():
    """Return a @tool-decorated function for report generation."""

    @tool
    def report_generation_subagent(report_title: str, report_data: str) -> str:
        """
        Format financial insights or anomaly findings into a markdown executive report.

        Args:
            report_title: Short title for the report (e.g. 'Q2 Anomaly Summary').
            report_data: The body content / findings to include in the report.
        """
        print("\n--- [Report Agent triggered] ---")
        report = (
            f"# EXECUTIVE REPORT: {report_title.upper()}\n"
            f"Generated by: Invoxio AI Platform\n"
            f"{'─' * 40}\n\n"
            f"## Findings Summary\n"
            f"{report_data}\n\n"
            f"## Recommendations\n"
            f"1. Investigate any highlighted anomalies immediately.\n"
            f"2. Review automated extraction logs weekly.\n"
            f"3. Schedule a follow-up audit within 30 days."
        )
        return report

    return report_generation_subagent
